# Generated by Django 2.1.4 on 2018-12-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
